export const products = [
  {
    id: 1,
    name: "iPhone 14",
    category: "Phones",
    price: 799,
    brand: "Apple",
    rating: 4.8,
    description: "128GB OLED smartphone with excellent camera performance.",
  },
  {
    id: 2,
    name: "Samsung Galaxy A54",
    category: "Phones",
    price: 449,
    brand: "Samsung",
    rating: 4.6,
    description: "Balanced mid-range phone with bright AMOLED display.",
  },
  {
    id: 3,
    name: "Google Pixel 8a",
    category: "Phones",
    price: 499,
    brand: "Google",
    rating: 4.7,
    description: "Clean Android experience with excellent AI-assisted camera tools.",
  },
  {
    id: 4,
    name: "OnePlus Nord 3",
    category: "Phones",
    price: 399,
    brand: "OnePlus",
    rating: 4.5,
    description: "Fast charging phone with smooth performance and OLED screen.",
  },
  {
    id: 5,
    name: "Dell XPS 13",
    category: "Laptops",
    price: 1299,
    brand: "Dell",
    rating: 4.8,
    description: "Premium ultrabook with a sharp display and lightweight design.",
  },
  {
    id: 6,
    name: "Acer Nitro 5",
    category: "Laptops",
    price: 899,
    brand: "Acer",
    rating: 4.5,
    description: "Gaming laptop with discrete graphics and a high-refresh screen.",
  },
  {
    id: 7,
    name: "Lenovo IdeaPad Gaming 3",
    category: "Laptops",
    price: 749,
    brand: "Lenovo",
    rating: 4.4,
    description: "Affordable gaming laptop with a solid CPU/GPU combo.",
  },
  {
    id: 8,
    name: "MacBook Air M2",
    category: "Laptops",
    price: 1199,
    brand: "Apple",
    rating: 4.9,
    description: "Efficient everyday laptop with long battery life and a silent design.",
  },
  {
    id: 9,
    name: "Sony WH-1000XM5",
    category: "Headphones",
    price: 349,
    brand: "Sony",
    rating: 4.9,
    description: "Industry-leading noise cancellation and rich sound quality.",
  },
  {
    id: 10,
    name: "Apple AirPods Pro 2",
    category: "Headphones",
    price: 249,
    brand: "Apple",
    rating: 4.8,
    description: "Compact wireless earbuds with adaptive transparency and ANC.",
  },
  {
    id: 11,
    name: "Jabra Elite 8 Active",
    category: "Headphones",
    price: 229,
    brand: "Jabra",
    rating: 4.6,
    description: "Durable wireless earbuds with strong battery life and secure fit.",
  },
  {
    id: 12,
    name: "Samsung Galaxy Watch 6",
    category: "Smart Watches",
    price: 299,
    brand: "Samsung",
    rating: 4.7,
    description: "Feature-rich smartwatch with fitness tracking and vivid AMOLED display.",
  },
  {
    id: 13,
    name: "Apple Watch SE (2nd Gen)",
    category: "Smart Watches",
    price: 249,
    brand: "Apple",
    rating: 4.8,
    description: "Affordable smartwatch with core health features and smooth iPhone integration.",
  },
  {
    id: 14,
    name: "Garmin Venu 3",
    category: "Smart Watches",
    price: 449,
    brand: "Garmin",
    rating: 4.8,
    description: "Fitness-focused smartwatch with advanced health metrics and battery life.",
  },
  {
    id: 15,
    name: "iPad 10th Gen",
    category: "Tablets",
    price: 349,
    brand: "Apple",
    rating: 4.7,
    description: "Versatile tablet for entertainment, note-taking, and everyday browsing.",
  },
  {
    id: 16,
    name: "Samsung Galaxy Tab S9 FE",
    category: "Tablets",
    price: 449,
    brand: "Samsung",
    rating: 4.6,
    description: "Well-balanced tablet with a sharp display and productivity-friendly features.",
  }
];
